export declare const env: {
    ANTHROPIC_API_KEY: string;
    SUPABASE_URL: string;
    SUPABASE_SERVICE_KEY: string;
    REDIS_URL: string;
    MOBILE_ACCESS_TOKEN: string;
    PC_AGENT_TOKEN: string;
    WEBHOOK_SECRET: string;
    SESSION_SECRET: string;
    PUSHOVER_USER_KEY: string;
    PUSHOVER_APP_TOKEN: string;
    ELEVENLABS_API_KEY: string;
    ELEVENLABS_VOICE_ID: string;
    GITHUB_DEFAULT_REPO: string;
    PORT: number;
    NODE_ENV: "development" | "production" | "test";
    BACKEND_URL: string;
    WS_URL: string;
    GITHUB_TOKEN?: string | undefined;
    GITHUB_OWNER?: string | undefined;
    GOOGLE_CLIENT_ID?: string | undefined;
    GOOGLE_CLIENT_SECRET?: string | undefined;
    GOOGLE_REDIRECT_URI?: string | undefined;
    VERCEL_TOKEN?: string | undefined;
    NETLIFY_TOKEN?: string | undefined;
    RAILWAY_TOKEN?: string | undefined;
    RAILWAY_PROJECT_ID?: string | undefined;
    RAILWAY_SERVICE_ID?: string | undefined;
    SUPABASE_ACCESS_TOKEN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_WHATSAPP_FROM?: string | undefined;
    GOOGLE_SERVICE_ACCOUNT_JSON?: string | undefined;
    PEXELS_API_KEY?: string | undefined;
    CLOUDINARY_CLOUD_NAME?: string | undefined;
    CLOUDINARY_API_KEY?: string | undefined;
    CLOUDINARY_API_SECRET?: string | undefined;
    ASSEMBLYAI_API_KEY?: string | undefined;
    TELEGRAM_BOT_TOKEN?: string | undefined;
    TELEGRAM_CHAT_ID?: string | undefined;
    TELEGRAM_ALLOWED_CHATS?: string | undefined;
    TELEGRAM_ADMIN_IDS?: string | undefined;
    TIKTOK_ACCESS_TOKEN?: string | undefined;
    TIKTOK_OPEN_ID?: string | undefined;
    KLING_API_KEY?: string | undefined;
    REPLICATE_API_TOKEN?: string | undefined;
    FAL_KEY?: string | undefined;
    FAL_API_KEY?: string | undefined;
    RUNWAY_API_KEY?: string | undefined;
    APIFY_API_KEY?: string | undefined;
    JINA_API_KEY?: string | undefined;
    GOOGLE_SEARCH_API_KEY?: string | undefined;
    GOOGLE_SEARCH_ENGINE_ID?: string | undefined;
    GROQ_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
};
export type Env = typeof env;
export declare function isTelegramAdmin(chatId: number): boolean;
//# sourceMappingURL=env.d.ts.map